### PR TITLE
Upgrade to `prost-0.5` and `prost-derive-0.5`; `dyn Future` warning

### PR DESCRIPTION
**Pull request by kathampy**
Not sure what additional tests are required.

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]

**Comment by kathampy** [comment]
Can you publish a new release?

**Comment by JohnTitor** [comment]
Waiting for the owner's decision.

**Comment by fafhrd91** [comment]
@JohnTitor teams added

**Comment by kathampy** [comment]
Do you plan to make a new minor release with these changes or should I maintain my local repo until the next one?

**Comment by JohnTitor** [comment]
@fafhrd91 What about new release?

**Comment by fafhrd91** [comment]
added core team to owners

**Comment by JohnTitor** [comment]
Okay, I'll release this as a new patch version.

**Comment by JohnTitor** [comment]
Just made a new release!

**Pull request merged**
